### PR TITLE
Time is optional

### PR DESCRIPTION
**Pull request by gasche**
configure.ac: make the `time` command optional

The `time` command is only required for the `benchmarks` Makefile
target which is only used for development, not for installing the
package. It is unfortunate to block installation on systems that could
perfectly support it (the problem is compounded by the fact that the
target uses GNU-specific time options that are not available on the
`time` command of BSD or OSX systems).

This change makes the configure only warn, instead of erroring, if
`time` is missing. I checked that the rest of the build goes perfectly
well -- except the `benchmarks` rule is now a no-op.

See ocaml/opam-repository#9832, which was blocked by a
`time`-related failure with `bitstring` on CentOS, and see
the discussion in ocaml/opam-repository#9848.

### CODE REVIEW

**Comment by gasche** [comment]
Oops, that sounds like a temporary break-things-to-check-they-break change that was pushed too soon.

**Comment by gasche** [comment]
This is now fixed. Thanks for catching it!

**Comment by xguerin** [comment]
Thanks !

**Comment by gasche** [comment]
Thanks! It might be useful to make a release (this can be very ligthweight: just adding a tag and pushing it to github suffices) so that the version without the dependency can be used for OPAM packaging.

**Pull request merged**
